
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.assofjpybasic.backend.analizador;

/** CUP generated class containing symbol constants. */
public class SintaxisPrincipalSym {
  /* terminals */
  public static final int esp = 7;
  public static final int com = 8;
  public static final int java = 3;
  public static final int txt = 6;
  public static final int EOF = 0;
  public static final int prog = 5;
  public static final int vb = 2;
  public static final int error = 1;
  public static final int py = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "vb",
  "java",
  "py",
  "prog",
  "txt",
  "esp",
  "com"
  };
}

