
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.assofjpybasic.backend.analizador.python;

/** CUP generated class containing symbol constants. */
public class SintaxisPythonSym {
  /* terminals */
  public static final int newline = 54;
  public static final int floatinput = 36;
  public static final int mod = 26;
  public static final int potig = 43;
  public static final int floor = 27;
  public static final int com = 46;
  public static final int menosig = 39;
  public static final int coma = 31;
  public static final int dedent = 53;
  public static final int igual = 37;
  public static final int range = 12;
  public static final int nott = 4;
  public static final int mayorig = 20;
  public static final int string = 51;
  public static final int menorig = 18;
  public static final int indent = 52;
  public static final int masig = 38;
  public static final int elsee = 9;
  public static final int porig = 40;
  public static final int andd = 5;
  public static final int intinput = 35;
  public static final int charinput = 34;
  public static final int returnn = 3;
  public static final int menos = 23;
  public static final int menor = 17;
  public static final int elseiff = 8;
  public static final int iff = 7;
  public static final int EOF = 0;
  public static final int dosp = 32;
  public static final int parc = 30;
  public static final int mas = 22;
  public static final int whilee = 13;
  public static final int para = 29;
  public static final int error = 1;
  public static final int mayor = 19;
  public static final int breakk = 14;
  public static final int entero = 48;
  public static final int pot = 28;
  public static final int por = 24;
  public static final int forr = 10;
  public static final int floorig = 42;
  public static final int id = 47;
  public static final int divig = 41;
  public static final int orr = 6;
  public static final int noigual = 16;
  public static final int inn = 11;
  public static final int modig = 44;
  public static final int puntocoma = 45;
  public static final int igig = 21;
  public static final int continuee = 15;
  public static final int print = 33;
  public static final int character = 50;
  public static final int div = 25;
  public static final int decimal = 49;
  public static final int deff = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "deff",
  "returnn",
  "nott",
  "andd",
  "orr",
  "iff",
  "elseiff",
  "elsee",
  "forr",
  "inn",
  "range",
  "whilee",
  "breakk",
  "continuee",
  "noigual",
  "menor",
  "menorig",
  "mayor",
  "mayorig",
  "igig",
  "mas",
  "menos",
  "por",
  "div",
  "mod",
  "floor",
  "pot",
  "para",
  "parc",
  "coma",
  "dosp",
  "print",
  "charinput",
  "intinput",
  "floatinput",
  "igual",
  "masig",
  "menosig",
  "porig",
  "divig",
  "floorig",
  "potig",
  "modig",
  "puntocoma",
  "com",
  "id",
  "entero",
  "decimal",
  "character",
  "string",
  "indent",
  "dedent",
  "newline"
  };
}

